### PR TITLE
Update build with a more recent parent

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
Please @reviewbybees

**Comment by aheritier** [comment]
Thanks for the notice @daniel-beck This plugin shouldn't be impacted by https://issues.jenkins-ci.org/browse/JENKINS-39154 but I preferred to not take any risk and updated to 2.16

**Comment by batmat** [comment]
:bee:

**Comment by aheritier** [comment]
thx @pellepelster 
If you have any issue with the release don't hesitate to ping me on IRC or by email

**Pull request merged**
